import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {once} from 'node:events';import {createServer} from './src/server.mjs';import {evaluateAccess,isDescendant} from './src/policy.mjs';import {sha256} from './src/config.mjs';
const organizations=[{id:'black-sands-ventures',parent_id:null,status:'active'},{id:'roll-call',parent_id:'black-sands-ventures',status:'active'},{id:'asmbly',parent_id:'black-sands-ventures',status:'active'},{id:'roll-call-events',parent_id:'roll-call',status:'active'}];
const grants=[{role:'owner',resource:'work',action:'read',inherit_descendants:true},{role:'operator',resource:'work',action:'read',inherit_descendants:false},{role:'operator',resource:'calendar',action:'read',inherit_descendants:false}];
test('organization descendant graph is directional',()=>{assert.equal(isDescendant(organizations,'roll-call-events','black-sands-ventures'),true);assert.equal(isDescendant(organizations,'asmbly','roll-call'),false);});
test('BSV owner inherits work read to descendants',()=>{const d=evaluateAccess({organizations,memberships:[{organization_id:'black-sands-ventures',role:'owner',status:'active'}],grants,organizationId:'roll-call-events',resource:'work',action:'read'});assert.equal(d.allow,true);assert.equal(d.reason,'inherited_descendant_scope');});
test('Roll Call operator cannot cross into ASMBLY',()=>{const d=evaluateAccess({organizations,memberships:[{organization_id:'roll-call',role:'operator',status:'active'}],grants,organizationId:'asmbly',resource:'work',action:'read'});assert.equal(d.allow,false);assert.equal(d.reason,'organization_scope_denied');});
test('identity permission claims are irrelevant without membership',()=>{const d=evaluateAccess({organizations,memberships:[],grants,organizationId:'roll-call',resource:'work',action:'read'});assert.equal(d.allow,false);assert.equal(d.reason,'subject_no_membership');});
const receipts=[];const store={ready:async()=>true,authorizationData:async i=>({organizations,memberships:i.subjectId==='owner-sub'?[{issuer:i.issuer,subject_id:i.subjectId,organization_id:'black-sands-ventures',role:'owner',status:'active'}]:[],grants}),receipt:async x=>(receipts.push(x),x),getReceipt:async id=>receipts.find(x=>x.id===id)||null};
const cfg={port:0,environment:'staging',serviceId:'platform-access:p3.3-test',issuer:'https://identity.test/realms/bsv-shared',audience:'omni-preview',serviceKeyHash:sha256('test-service-key'),policyVersion:'P3.3.0',db:{host:'x',port:5432,database:'x',user:'x',password:'x',ssl:false}};
const verify=async token=>token==='owner-token'?{ok:true,identity:{issuer:cfg.issuer,subjectId:'owner-sub',acr:'aal2'}}:token==='outsider-token'?{ok:true,identity:{issuer:cfg.issuer,subjectId:'outsider',acr:'aal1'}}:{ok:false,error:'identity_signature_invalid'};
let server,base;test.before(async()=>{server=createServer(cfg,{store,verifyIdentity:verify});server.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;});test.after(()=>server.close());
async function post(body,key='test-service-key'){const r=await fetch(base+'/v1/access/decisions',{method:'POST',headers:{'content-type':'application/json','x-platform-service-key':key},body:JSON.stringify(body)});return {r,b:await r.json()};}
test('service authentication fails closed',async()=>{const {r,b}=await post({identity_token:'owner-token',organization_id:'roll-call',resource:'work',action:'read'},'wrong');assert.equal(r.status,401);assert.equal(b.error,'service_auth_required');});
test('invalid identity denies and records receipt',async()=>{const {r,b}=await post({identity_token:'bad',organization_id:'roll-call',resource:'work',action:'read'});assert.equal(r.status,401);assert.equal(b.decision,'deny');assert.ok(b.receipt_id);});
test('owner token allows descendant read with receipt',async()=>{const {r,b}=await post({identity_token:'owner-token',organization_id:'roll-call-events',resource:'work',action:'read'});assert.equal(r.status,200);assert.equal(b.decision,'allow');assert.ok(b.receipt_id);});
test('outsider token cannot self-authorize',async()=>{const {r,b}=await post({identity_token:'outsider-token',organization_id:'roll-call',resource:'work',action:'read'});assert.equal(r.status,200);assert.equal(b.decision,'deny');assert.equal(b.reason,'subject_no_membership');});
test('receipt can be read by authenticated service',async()=>{const allowed=receipts.find(x=>x.decision==='allow');const r=await fetch(base+'/v1/audit/receipts/'+allowed.id,{headers:{'x-platform-service-key':'test-service-key'}});assert.equal(r.status,200);const b=await r.json();assert.equal(b.receipt.id,allowed.id);});
